AWSTemplateFormatVersion: "2010-09-09"
Description: "Master Template"
Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      StackName: my-vpc-stack
      TemplateURL: 'https://bastion-cfn-tamplate.s3.us-east-1.amazonaws.com/vpc-tamplate.yaml' # This should be the S3 URL for the VPC template

  PublicEC2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      StackName: my-public-ec2-stack
      TemplateURL: 'https://bastion-cfn-tamplate.s3.us-east-1.amazonaws.com/public-ec2.yaml' # S3 URL for the public EC2 template
      Parameters:
        VPCId: !GetAtt VPCStack.Outputs.VPCId
        PublicSubnetId: !GetAtt VPCStack.Outputs.PublicSubnetId

  PrivateEC2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      StackName: my-private-ec2-stack
      TemplateURL: 'https://bastion-cfn-tamplate.s3.us-east-1.amazonaws.com/private-ec2.yaml' # S3 URL for the private EC2 template
      Parameters:
        VPCId: !GetAtt VPCStack.Outputs.VPCId
        PrivateSubnetId: !GetAtt VPCStack.Outputs.PrivateSubnetId
        BastionPublicIP: !GetAtt PublicEC2Stack.Outputs.PublicIP

Outputs:
  VPCId:
    Value: !GetAtt VPCStack.Outputs.VPCId
    Description: VPC ID

  PublicIP:
    Value: !GetAtt PublicEC2Stack.Outputs.PublicIP
    Description: Public IP of the public EC2 instance
