AWSTemplateFormatVersion: '2010-09-09'
Description: 'Master template for nested stack deployment'

Parameters:
  UseKeyPair:
    Type: String
    Default: 'false'
    AllowedValues: ['true', 'false']
    Description: 'Choose whether to create and use an SSH key pair'

  KeyPairName:
    Type: String
    Default: ''
    Description: 'Name for the SSH key pair (if UseKeyPair is true)'

  PublicInstancePassword:
    Type: String
    NoEcho: true
    MinLength: 8
    MaxLength: 41
    Description: Password for public instance (min 8 chars, must include letters, numbers, and special chars)
    ConstraintDescription: Password must be between 8 and 41 characters

  PrivateInstancePassword:
    Type: String
    NoEcho: true
    MinLength: 8
    MaxLength: 41
    Description: Password for private instance (min 8 chars, must include letters, numbers, and special chars)
    ConstraintDescription: Password must be between 8 and 41 characters

Conditions:
  CreateKeyPair: !Equals [!Ref UseKeyPair, 'true']

Resources:
  SSHKeyPair:
    Type: AWS::EC2::KeyPair
    Condition: CreateKeyPair
    Properties:
      KeyName: !Ref KeyPairName

  PublicInstancePasswordParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/ec2/password/${AWS::StackName}/public'
      Type: String
      Value: !Ref PublicInstancePassword

  PrivateInstancePasswordParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/ec2/password/${AWS::StackName}/private'
      Type: String
      Value: !Ref PrivateInstancePassword

  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'https://cfn-bastion-host.s3.us-east-1.amazonaws.com/vpc-tamplate.yaml'
      TimeoutInMinutes: 20

  PublicEC2Stack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: 'https://cfn-bastion-host.s3.us-east-1.amazonaws.com/public-ec2.yaml'
      Parameters:
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        PublicSubnetId: !GetAtt VPCStack.Outputs.PublicSubnetId
        UseKeyPair: !Ref UseKeyPair
        KeyName: !If [CreateKeyPair, !Ref SSHKeyPair, '']
        PasswordParameter: !Ref PublicInstancePasswordParam
      TimeoutInMinutes: 20

  PrivateEC2Stack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: 'https://cfn-bastion-host.s3.us-east-1.amazonaws.com/private-ec2.yaml'
      Parameters:
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        PrivateSubnetId: !GetAtt VPCStack.Outputs.PrivateSubnetId
        UseKeyPair: !Ref UseKeyPair
        KeyName: !If [CreateKeyPair, !Ref SSHKeyPair, '']
        PasswordParameter: !Ref PrivateInstancePasswordParam
      TimeoutInMinutes: 20

Outputs:
  PublicInstanceIP:
    Description: Public IP of the web server
    Value: !GetAtt PublicEC2Stack.Outputs.PublicIP
  PrivateInstanceIP:
    Description: Private IP of the private instance
    Value: !GetAtt PrivateEC2Stack.Outputs.PrivateIP
  KeyPairName:
    Description: Name of the created key pair (if key pair was created)
    Condition: CreateKeyPair
    Value: !Ref SSHKeyPair