AWSTemplateFormatVersion: "2010-09-09"
Description: "Master Template"
Resources:
  PublicEC2KeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: PublicEC2Key
      KeyType: rsa
      Tags:
        - Key: Name
          Value: PublicEC2Key

  PrivateEC2KeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: PrivateEC2Key
      KeyType: rsa
      Tags:
        - Key: Name
          Value: PrivateEC2Key

Outputs:
  PublicEC2KeyPairName:
    Value: !Ref PublicEC2KeyPair
    Export:
      Name: PublicEC2KeyPair

  PrivateEC2KeyPairName:
    Value: !Ref PrivateEC2KeyPair
    Export:
      Name: PrivateEC2KeyPair

