AWSTemplateFormatVersion: "2010-09-09"
Description:
  "Bastion EC2 Instance that have private access on port 22 through bastion host"
Resources:
  PrivateEC2:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1b
      ImageId: ami-0a3c3a20c09d6f377
      SubnetId: !ImportValue PrivateSubnet
      InstanceType: t2.micro
      KeyName: !ImportValue PrivateEC2KeyPair
      SecurityGroupIds:
        - !Ref SSHSecurityGroup

  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH traffic from public EC2
      VpcId: !ImportValue VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "22"
          ToPort: "22"
          CidrIp: !ImportValue PublicIP



