AWSTemplateFormatVersion: '2010-09-09'
Description: 'Public EC2 instance with Apache'

Parameters:
  VpcId:
    Type: String
    Description: VPC ID
  PublicSubnetId:
    Type: String
    Description: Public Subnet ID
  UseKeyPair:
    Type: String
    AllowedValues: ['true', 'false']
    Description: Whether to use SSH key pair
  KeyName:
    Type: String
    Description: Name of the SSH key pair
    Default: ''
  PasswordParameter:
    Type: String
    Description: SSM Parameter name for instance password

Conditions:
  UseSSHKey: !Equals [!Ref UseKeyPair, 'true']

Resources:
  PublicEC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP and SSH access
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  PublicEC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Policies:
        - PolicyName: AllowSSMSessionToPrivateInstance
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: ssm:StartSession
                Resource: 'arn:aws:ec2:us-east-1:284678542894:instance/i-038d6bb8e10480e16'

  PublicEC2Profile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref PublicEC2Role

  PublicEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-063d43db0594b521b
      InstanceType: t2.micro
      SubnetId: !Ref PublicSubnetId
      SecurityGroupIds:
        - !Ref PublicEC2SecurityGroup
      KeyName: !If [UseSSHKey, !Ref KeyName, !Ref 'AWS::NoValue']
      IamInstanceProfile: !Ref PublicEC2Profile
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd jq aws-cli
          systemctl start httpd
          systemctl enable httpd
          echo "<h1>Hello from Public Instance</h1>" > /var/www/html/index.html

          # Set up password authentication
          PASSWORD=$(aws ssm get-parameter --name ${PasswordParameter} --with-decryption --region ${AWS::Region} --query Parameter.Value --output text)
          useradd ec2-user
          echo "$PASSWORD" | passwd ec2-user --stdin
          sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sed -i 's/PermitRootLogin yes/PermitRootLogin no/' /etc/ssh/sshd_config

          # If not using key pair, disable key authentication
          if [ "${UseKeyPair}" = "false" ]; then
            sed -i 's/PubkeyAuthentication yes/PubkeyAuthentication no/' /etc/ssh/sshd_config
          fi

          systemctl restart sshd

Outputs:
  PublicEC2SecurityGroupId:
    Description: Security Group ID of the Public EC2 Instance
    Value: !Ref PublicEC2SecurityGroup