AWSTemplateFormatVersion: "2010-09-09"
Description:
  "Public EC2 Instance that have public access on port 80 and will connect to private EC2 instance through SSH"
Parameters:
  VPCId:
    Type: AWS::EC2::VPC::Id
  PublicSubnetId:
    Type: AWS::EC2::Subnet::Id

Resources:
  PublicEC2:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-063d43db0594b521b
      InstanceType: t2.micro
      SubnetId: !Ref PublicSubnet
      SecurityGroups:
        - !Ref HTTPSecurityGroup
      # we install our web server with user data
      UserData:
        Fn::Base64: |
          #!/bin/bash -xe
          dnf update -y
          dnf install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "<h1>Hello World from user data</h1>" > /var/www/html/index.html

  HTTPSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: HTTP
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 80
          IpProtocol: tcp
          ToPort: 80

Outputs:
  PublicEC2Id:
    Value: !Ref PublicEC2
